In [1]:
import pandas as pd

orders = pd.read_csv('orders.csv')

products = pd.read_csv('products.csv')

customers = pd.read_csv('customers.csv')
print(orders)
print(products)
print(customers)

    order_id  customer_id product_id  quantity     timestamp
0          1          122       1051         5  1/17/24 1:24
1          2          123       1064       555  9/12/23 1:24
2          3          124      1092          3  2/12/24 1:24
3          4          125       1077         5  1/17/24 1:24
4          5          126       1090         6  9/12/23 1:24
5          6          127      1092          4  2/12/24 1:24
6          7          128       1103         7  1/17/24 1:24
7          8          129       1116       344  9/12/23 1:24
8          9          130      1092          5  2/12/24 1:24
9         10          131       1129       123  1/17/24 1:24
10        11          132       1142       535  9/12/23 1:24
11        12          133      1092       1124  2/12/24 1:24
12        13          134       1155       235  1/17/24 1:24
13        14          135       1168      4345  9/12/23 1:24
14        15          136      1092       5435  2/12/24 1:24
15        16          137       1181        34  1/17/24 1:24
16        17          138       1194        43  9/12/23 1:24
17        18          139      1092         56  2/12/24 1:24
18        19          140       1207       234  1/17/24 1:24
19        20          141       1220       456  9/12/23 1:24
20        21          142      1092         56  2/12/24 1:24
21        22          143       1233        77  1/17/24 1:24
22        23          144       1246        35  9/12/23 1:24
23        24          145      1092         23  2/12/24 1:24
24        25          146       1259      1133  1/17/24 1:24
25        26          147       1272        54  9/12/23 1:24
26        27          148      1092         64  2/12/24 1:24
27        28          149       1285        35  1/17/24 1:24
28        29          150       1298       123  9/12/23 1:24
    product_id product_description  product_price
0            1          Yellow Hat          55.00
1            2          Red Jacked          34.00
2            3        Orange Skirt          23.00
3            4         Blue Tshirt          15.99
4            5        White Shorts          16.99
5            6        Silver Skirt          23.88
6            7         Brown Socks          35.77
7            8          Gray Pants          35.53
8            9         White Pants          25.99
9           10        Office Pants          23.99
10          11        Purple Pants          11.99
11          12        Purple Shoes          35.99
12          13      Lavender Dress          12.66
13          14        White  Dress          14.99
14          15        Brown Jacket          35.99
15          16        Brown Jacket           3.99
16          17        Black Jacket           1.99
17          18           Red Skirt           3.99
18          19        Orange Socks           4.88
19          20         Black Dress           5.99
20          21           White Bag           2.99
21          22           Black Bag           7.99
22          23       Orange Thirts           1.00
23          24        White Tshirt           2.99
24          25        Black Tshirt           4.99
25          26        Orange Dress           5.99
26          27          Pink Dress           6.88
27          28           Red Dress         999.00
28          29        Velvet Dress           5.99
    customer_id      customer_name  \
0          1246         Jane Ostin
1          1247        Joseph Will
2          1248    Williams Dorman
3          1249        Dima Gordon
4          1250       Alex William
5          1251        Dan Nicolau
6          1252     Julia Liberman
7          1253       Tania Gofman
8          1254     Joseph Gophman
9          1255       Joe Tribiani
10         1256        Ross Geller
11         1257      Monica Geller
12         1258       Chenler Bing
13         1259       Rachel Green
14         1260         Ema Geller
15         1261       Pheobe Buffe
16         1262        Tom Watson
17         1263         Ama Geller
18         1264        Alex Fahman
19         1265       Ola Al Behan
20         1266        Anna Aniani
21         1267   Giovani Tripiani
22         1268      Ross Tripiani
23         1269      Frank Van Gof
24         1270       Tom Peterson
25         1271       Peter Danski
26         1272  Piotrki Barnonski
27         1273      Elene Koriani
28         1274     Sanda Petriani

                                customer_address customer_phone_number
0        123 Maple Street, Springfield, IL 62704        (312) 555-0123
1               456 Oak Avenue, Denver, CO 80203        (213) 555-0456
2                789 Pine Drive, Miami, FL 33101        (415) 555-0789
3               101 Birch Lane, Austin, TX 78701        (617) 555-1011
4               202 Elm Court, Seattle, WA 98101        (305) 555-1314
5               303 Cedar Road, Boston, MA 02108        (720) 555-1617
6        404 Spruce Boulevard, Phoenix, AZ 85001        (602) 555-1919
7            505 Willow Place, Chicago, IL 60601        (503) 555-2121
8               606 Cherry Way, Dallas, TX 75201        (404) 555-2323
9       707 Magnolia Avenue, San Diego, CA 92101        (612) 555-2525
10      808 Palm Street, San Francisco, CA 94101        (718) 555-2727
11           909 Ash Terrace, Portland, OR 97201        (702) 555-2929
12         121 Juniper Circle, Atlanta, GA 30301        (901) 555-3131
13          232 Fir Trail, Minneapolis, MN 55401        (510) 555-3434
14           343 Redwood Row, New York, NY 10001        (919) 555-3636
15             454 Aspen Path, Orlando, FL 32801        (504) 555-3838
16  565 Hickory Crossing, Philadelphia, PA 19101        (614) 555-4040
17          676 Poplar Meadow, Detroit, MI 48201        (704) 555-4242
18        787 Cypress Grove, Nashville, TN 37201        (317) 555-4444
19           898 Beech Bend, Las Vegas, NV 89101        (816) 555-4646
20  919 Sycamore Ridge, Salt Lake City, UT 84101        (414) 555-4848
21        212 Holly Crest, New Orleans, LA 70112        (281) 555-5050
22       323 Laurel Street, Pittsburgh, PA 15201        (202) 555-5252
23            434 Alder Lane, Columbus, OH 43201        (801) 555-5454
24      545 Dogwood Heights, Charlotte, NC 28201        (917) 555-5656
25   656 Maplewood Drive, Indianapolis, IN 46201        (512) 555-5858
26    767 Birchwood Court, Kansas City, MO 64101        (770) 555-6060
27      878 Evergreen Trail, Milwaukee, WI 53201        (216) 555-6262
28           989 Walnut Ridge, Houston, TX 77001        (615) 555-6464